apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: myapp
          imagePullPolicy: IfNotPresent
          command: ["python"]
          args: ["manage.py", "migrate"]
      restartPolicy: Never
  backoffLimit: 4
